In [2]:
import numpy as np
print(np.__version__) # type of version and to check whether numpy install or not.

1.26.4


In [16]:
a=np.array([1,2,3,4,5]) # one dimension al array

In [57]:
a

array([ 1,  2,  3, 55, 65])

In [26]:
a[2] # accessing the elemnts using list

3

In [29]:
a[3]=7 # The array is mutable

In [30]:
a

array([1, 2, 3, 7, 5])

In [31]:
a[:4]  # Python slice notation can be used for indexing

array([1, 2, 3, 7])

In [44]:
a

array([ 1,  2,  3, 55, 65])

In [45]:
a.shape # shape tell about no.of columns and no.of rows 

(5,)

In [37]:
c=a[3:]

In [38]:
c

array([40,  5])

In [39]:
c[0]=55

In [41]:
c[1]=65

In [42]:
a

array([ 1,  2,  3, 55, 65])

In [18]:
b=np.array([[1,2,3,4,5],
           [5,6,7,8,9]]) # 2D array
#The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

In [19]:
b

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [21]:
b.shape

(2, 5)

# Array attributes

In [61]:
arr=np.array([1,2,3,4,5])

In [62]:
arr

array([1, 2, 3, 4, 5])

In [64]:
arr.ndim  # he number of dimensions of an array is contained in the ndim attribute.

1

In [69]:
ab=np.array([[1,23,45],[75,99,63]])

In [70]:
ab

array([[ 1, 23, 45],
       [75, 99, 63]])

In [71]:
ab.ndim

2

In [79]:
three=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[5,6,9]]])

In [80]:
three

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [5, 6, 9]]])

In [81]:
three.ndim # three dimensional

3

In [92]:
four=np.array([
    [[[1,2,3],[3,4,5]]],
              
              [[[4,5,7],[8,9,2]]]
              
              ])

In [93]:
four.ndim # Four dimensions

4

# Shape (pecify the number of elements along each dimension.)

In [95]:
arr.shape

(5,)

In [96]:
ab.shape

(2, 3)

In [97]:
three.shape

(2, 2, 3)

In [99]:
len(arr.shape)==arr.ndim

True

In [100]:
len(ab.shape)==ab.ndim

True

In [101]:
len(three)==three.ndim

False

# size 

In [102]:
a.size

5

In [103]:
ab.size

6

In [104]:
three.size

12

# dtype

In [106]:
a.dtype

dtype('int32')

In [109]:
arr.dtype

dtype('int32')

In [110]:
four.dtype

dtype('int32')